# Generated by Django 3.1.6 on 2021-02-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('post', 'post')], default='post', max_length=5),
        ),
    ]
