# Generated by Django 3.1.6 on 2021-02-15 22:31

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_author_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='type',
            field=models.CharField(default=main.models.UserType['author'], max_length=25),
        ),
    ]
