# Generated by Django 3.1.6 on 2021-02-19 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='author',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='items',
        ),
        migrations.AddField(
            model_name='inbox',
            name='authors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inbox',
            name='posts',
            field=models.ManyToManyField(blank=True, to='posts.Post'),
        ),
    ]
