# Generated by Django 3.1.6 on 2021-02-19 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inbox', '0002_auto_20210219_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='authors',
        ),
        migrations.AddField(
            model_name='inbox',
            name='author',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.author'),
            preserve_default=False,
        ),
    ]
