# Generated by Django 3.1.6 on 2021-02-15 22:04

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20210215_2146'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, follower=django.db.models.expressions.F('followed')), name='follower_not_equal_to_followed'),
        ),
    ]
